server:
  port: 8001
spring:
  # RestController返回json格式
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: webcenter-sample
  redis:
    host: localhost
    password: 123456
    port: 6379
    timeout: 60000
webcenter:
  server:
    host : localhost
    port: 8000
    clientid: WZUIIXWZUIIX
    secretkey: qOIWRbzeFvOnXUYTspfSt2ibfJPe1vtG