server:
  port: 8000
spring:
  application:
    name: webcenter-console
  # 返回json格式
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ### redis配置 db_redis需要在/etc/hosts里面添加: localhost db_redis
  redis:
    host: db_redis
    password: 123456
    port: 6379
    timeout: 60000
  ### 数据库配置 db_mysql需要在/etc/hosts里面添加: localhost db_mysql
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db_mysql:3306/webcenter?characterEncoding=utf8&useSSL=false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gaoqisen.webcenter.entity
webcenter:
  client:
    ### 前后端分离：true表示前后端分离，用于单点登录时重定向到前端的地址。false表示非前后端分离，可以不用配置host和prot
    forestage: false
    host: localhost
    port: 8080
  ### 定时消费redis list
  scheduled:
    cron: 0 0/1 * * * ?