version: '2.0'
services:
  db_mysql:
    restart: always
    image: mysql:5.7.22
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /Users/jasongao/Documents/docker/mysql/data:/var/lib/mysql
    networks:
      - net
  db_redis:
    image: redis
    container_name: db_redis
    command: redis-server --requirepass 123456
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - net
  my_webcenter:
    image: registry.cn-hangzhou.aliyuncs.com/gqs/webcenter:1.0.1
    container_name: my_webcenter
    ports:
      - "8000:8000"
    networks:
      - net
networks:
  net:
    external: 
      # 请先创建net_webcenter网络
      name: net_webcenter